### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by linakherchi** [codybreene/merkle_money#2]
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by linakherchi** [comment]
Thank you, Cody ! I saw you already pushed your FSP to github. This is great !
Some comments regarding your state shape: 

1. I don't see the logo key in the schema. Are you going to implement AWS?
2. You need an inside key of id for each key inside entities.

**Comment by codybreene** [comment]
Hi Lina - I wasn't planning on storing the logos inside my DB. What would be your recommendation?

**Comment by linakherchi** [comment]
If you are going to have a lot of images on your website, I recommend using AWS, which will make your app faster.
If you are not planning to have a lot of images on your website, it will save you time to only have them in the assets pipeline.

**Comment by codybreene** [comment]
I would say I'd have less than 100 images

**Comment by linakherchi** [comment]
If it will be less than 100 images, you can keep these only in the assets pipeline.

**Comment by codybreene** [comment]
Sounds good! I will update the cryptocurrencies table accordingly to include 'logo_url' as a column.

**Comment by linakherchi** [comment]
Sweet ! You also need to have an entities outside key for your cryptocurrencies, wallets, and recentActivity keys

**Comment by codybreene** [comment]
just added -- thanks!
