### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by linakherchi** [codybreene/merkle_money#5]
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-in-person/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

**Comment by linakherchi** [comment]
Profile pages for top five cryptocurrencies was an MVP you stated when you applied for cloning CoinBase, did you decide to omit it? If yes, please add another one or move a bonus one to the list of 4 MVPs you will need to build.

If you think you will not be able to get to your 4th MVP by the end of two weeks, totally fine  ! But make sure to add it so that you can get back to it by the end of the cohort

**Comment by codybreene** [comment]
Added it back in -- and made other necessary edits
