### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by codybreene** [codybreene/merkle_money#7]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by linakherchi** [comment]
1. As soon as I go to Merkle Money, there is an error popping up in the console regarding the existence of a css.reset file
<img width="1438" alt="Screen Shot 2020-01-08 at 5 15 16 PM" src="https://user-images.githubusercontent.com/51456702/72029366-8fc89280-323a-11ea-8b1a-a32c7aedc498.png">

2. I am not able to see errors if I try to signup with a username that already exists

**Comment by codybreene** [comment]
So for some reason, `user.save` is not returning anything -- it's not hitting the else block of my code so I never catch the error.

**Comment by codybreene** [comment]
![image](https://user-images.githubusercontent.com/5722230/72041204-be0c9900-325f-11ea-841b-701e39d3584d.png)

**Comment by codybreene** [comment]
ok, figured out both of the issues. Everything should be bug free now :)

**Comment by linakherchi** [comment]
Great ! I am glad you were able to figure it out

**Comment by linakherchi** [comment]
You can move on to the next feature ! Everything looks great on User Auth
